quarkus.google.cloud.project-id=${projectId}
quarkus.rest-client."no.roedt.hypersys.HypersysRestClient".url = ${hypersysBaseUrl}
#%dev.hypersysBaseUrl=http://localhost:${quarkus.http.port}/hypersys
projectId=hypersys-googledrive
secretManagerProjectId=${projectId}
hypersysBaseUrl=https://raudt.hypersys.no/